force-app/main/default/objects/Case_Backup__b/Case_Backup__b.object-meta.xml
<CustomObject>
    <label>Case Backup</label>
    <pluralLabel>Case Backups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Backup__b/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Backups</relationshipLabel>
    <relationshipName>Case_Backups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Backup__b/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountsController.cls
public without sharing class AccountsController {
    @AuraEnabled
    public static List <Account> getAccounts() {
        return [SELECT Id, name, industry, Type, NumberOfEmployees, TickerSymbol, Phone FROM Account ORDER BY createdDate ASC];
    }
    
    @AuraEnabled
    public static List <Case_Backup__b> getCaseBackup(String accountId) {
        System.debug('accountId:-->' + accountId);
        return [select Id, Account__c, Case_Number__c, Description__c, Subject__c from Case_Backup__b WHERE Account__c = : Id.valueOf(accountId)];
    }
	
    @AuraEnabled
    public static List <ContentDocumentLink> getContentDocumentLink() {
        return [SELECT ContentDocumentId,Id,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId = '0010b00002MT2neAAD'];
    }
    
    @AuraEnabled
    public static String delContentDocumentLink(String docId) {
        String res = 'success';
        delete [SELECT Id FROM ContentDocument WHERE Id =: Id.valueOf(docId)];
        //delete [SELECT Id FROM ContentDocument WHERE Id ='0690b000004xqOYAAY'];
        return res;
    }
}